### ISSUE TITLE
Could not execute JDBC batch update

### ISSUE THREAD

**Issue by Ning2018** [Ning2018/Bugs#1]
Aug 08, 2018 3:52:45 PM org.hibernate.impl.SessionFactoryObjectFactory addInstance
INFO: Not binding factory to JNDI, no JNDI name configured
Hibernate: select max(id) from t_directories
Hibernate: insert into t_directories (user, path, parent_path, dir, create_time, id) values (?, ?, ?, ?, ?, ?)
Aug 08, 2018 3:53:09 PM org.hibernate.util.JDBCExceptionReporter logExceptions
WARNING: SQL Error: 1062, SQLState: 23000
Aug 08, 2018 3:53:09 PM org.hibernate.util.JDBCExceptionReporter logExceptions
SEVERE: Duplicate entry 'abced-sdfdfsfdfdfd/' for key 'user'
Aug 08, 2018 3:53:09 PM org.hibernate.event.def.AbstractFlushingEventListener performExecutions
SEVERE: Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:266)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:167)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:606)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:709)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:678)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:321)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:116)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy1.save(Unknown Source)
	at service.DirectoryServiceImpl.addDirectory(DirectoryServiceImpl.java:42)
	at test.Test.main(Test.java:36)
Caused by: java.sql.BatchUpdateException: Duplicate entry 'abced-sdfdfsfdfdfd/' for key 'user'
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1257)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:943)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more

**Comment by Ning2018** [comment]
delete the existed row from the table, and press "apply".
